### ISSUE TITLE
error staring neutron service, using all-in-one, centos 7

### ISSUE THREAD

**Issue by hdb3** [puppetlabs/puppetlabs-openstack#171] opened 2015-04-13 16:57 UTC
After fixing the dependency for mariadb in place of mysql in centos 7 I succesfully installed puppetlabs-openstack.  However, neutron service does not start (msg in neutron/server.log: "Table 'neutron.ml2_gre_allocations' doesn't exist").

I'm a puppet virgin, but I know openstack.  It looks as if puppet either didn't do the dbsync, or maybe did it before the neutron config file(s) was complete.

My install config is very simple - I just changed IP interface networks/and addresses in allinone.yaml and reference allinone.yaml via hiera.conf:
```
[root@puppet ~]# cat /etc/puppet/hiera.yaml
---
:backends:
  - yaml
:yaml:
  :datadir: /etc/puppet/hieradata
:hierarchy:
  - allinone
```

Any advice gratefully received

**Comment by cmurphy** [comment] 2015-04-13 22:16
Based on http://www.madorn.com/juno-neutron-server-not-starting.html#.VSw-HpTF9Dk it would seem like your guess is correct. However, I'm not able to reproduce it, either when installing the modules from git or from the forge.

Did your puppet run complete successfully, with no errors? Did you see something like this in the puppet output:

```
Notice: /Stage[main]/Neutron::Server/Exec[neutron-db-sync]: Triggered 'refresh' from 1 events
```

You could paste your puppet run output using http://paste.openstack.org/

Could you double check that the IP addresses you set are correct for your node? If they are private addresses (e.g. 10.x.x.x or 192.168.x.x) you could paste that as well.

**Comment by cmurphy** [comment] 2015-04-13 22:25
This could be related to #99, are you seeing 

```
Error 400 on SERVER: Could not find resource 'Exec[neutron-db-sync]' for relationship from 'Class[Neutron::Db::Mysql]' on node ....
```

during your puppet run?

**Comment by cmurphy** [comment] 2015-04-27 18:16
I'm not able to debug this without more information, so I'm closing this for now. Feel free to reopen if you are able to provide more information.

**Closed by cmurphy** 2015-04-27 18:16 UTC
